import Head from 'next/head'
import { useEffect, useState } from "react";
import Image from 'next/image'
import Up from '../component/Weather/up'
import Down from '../component/Weather/down'


export default function Home() {
  const [data, setData] = useState();
  const [location, setLocation] = useState('London');

  const handleClick = (name) => {
    setLocation(name);
  };

  useEffect(() => {
    fetch(
      `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=imperal&appid=8121996065f431554d6b4473494161b5`)
    
      .then((res) => res.json())
      .then((res) => {
        setData(res)})
    // const searchLocation =(e) => {
      // if(e.key === 'Enter')
      
      //  })
        // setLocation();
      
    //   }
    // }
      
      // .catch((err) => console.error(err));
   // console.log(res.data);
  }, [location]);

if (!data) {
  return <div>Loading...</div>
}

  return (
    <div className="whole">
      <div  className="glasses">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      <Up  Data onClick={handleClick} location={location} data={data} />

      <Down Data onClick={handleClick} location={location} data={data}/>
      </div>
    </div>
  )
}
